# Generated by Django 4.1 on 2022-08-31 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='descriptions',
            new_name='description',
        ),
    ]
